# Generated by Django 2.2 on 2019-06-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hbprouser',
            name='age',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='hbprouser',
            name='e_mail',
            field=models.CharField(blank='False', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='hbprouser',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='hbprouser',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='hbprouser',
            name='nick_name',
            field=models.CharField(blank='False', default='', max_length=50, null='False'),
        ),
        migrations.AlterField(
            model_name='hbprouser',
            name='number_phone',
            field=models.IntegerField(blank='False', default=0, null='True'),
        ),
        migrations.AlterField(
            model_name='hbprouser',
            name='password',
            field=models.CharField(blank='False', default='', max_length=100),
        ),
    ]
