# Generated by Django 2.2 on 2019-06-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190618_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hbprouser',
            name='age',
            field=models.IntegerField(blank='False', default=18),
        ),
        migrations.AlterField(
            model_name='hbprouser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
